version: '3.7'
services:
  dev_mysql:
    image: mysql:latest
    container_name: dev_mysql
    command: --default-authentication-plugin=mysql_native_password
  
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "kostroma_heatmap"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "seizures"
      MYSQL_ROOT_PASSWORD: "seizures"

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: dev_mysql
    ports:
      - 8080:8080

volumes:
  mysql_db_data_container:
